version: '3.8'
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_DEV_HOST}:${LOCAL_DB_PORT}:3306
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_DEV_HOST}:${ADMINER_PORT}:8080

volumes:
  db_data:
